# This is made for your config stuff not common with CrewCall Base.
# parameters.yml is for the instance-specific config (DB username and password
# better not be common between dev and prod for example) , this is for the
# application specific.

parameters:
    # You may want to change these.
    # Languange - No translations yet, so this is mere sugar.
    locale: en_GB

    # Javascripts Intl uses two-letter locale. And it should be decided by the
    # browser/client. Somehow that is broken.
    javascript_locale: en

    # Fullcalendar also use locale, but it may not have what you set above.
    # Check https://github.com/fullcalendar/fullcalendar/tree/master/locales
    # Use the filename without .js
    # If you set "all" it will load the all.js file instead. It's close to 200K
    # where the separate files are 3K.
    fullcalendar_locale: en-gb

    # This is for setting up the address fields. Different countries has
    # different needs, so we need somewhere for defining those needs.
    # Fields you can use is in Entity/EmbeddableAddress in the CrewCallBundle
    # code.
    # Country differs that it will not be showwn if it is the default country.
    # The values here is the ones shown in the input and edit forms.
    addressing:
        # Mostly, postal address as an extra address is not used. If you want
        # it, set it to true.
        use_postal_address: false
        default_country_code: NO
        default_country_name: Norway
        format:
            - ['addressLine1']
            - ['addressLine2']
            - ['postalCode', 'postalName']
            # This is the country code. Which may not be very useful.
            # - ['country']

    personfields:
        email:
            enabled: true
            attribute: false
            user_editable: true
        first_name:
            enabled: true
            attribute: false
            user_editable: true
        last_name:
            enabled: true
            attribute: false
            user_editable: true
        date_of_birth:
            enabled: false
            attribute: false
            user_editable: true
        diets:
            enabled: true
            attribute: false
            user_editable: true
        workload_percentage:
            enabled: false
            attribute: false
            user_editable: false
        nationality:
            enabled: false
            attribute: false
            user_editable: true
        emergency_contact:
            enabled: false
            attribute: false
            user_editable: true
        mobile_phone_number:
            enabled: true
            attribute: false
            user_editable: true
        address:
            enabled: true
            attribute: false
            user_editable: true
        home_phone_number:
            enabled: false
            attribute: false
            user_editable: false
        postal_address:
            # And yes, you have to enable addressing_config.use_postal_address
            enabled: false
            attribute: false
            user_editable: false
        # Not entirely personfields, but nice to configure.
        hours:
            enabled: true
            attribute: false
            user_editable: false
        profile_picture:
            enabled: true
            attribute: false
            user_editable: true
        functions:
            enabled: true
            attribute: false
            user_editable: false
        # Viewing and adding/removing ALL files.
        files:
            enabled: false
            attribute: false
            user_editable: false

    # This basically says itself - Maybe false should be default, but at least
    # it'll show that registration is possible.
    # But if you want to turn this on you must also comment out the
    # registration routes in routing_custom.yml
    allow_registration: true
    # This also basically says itself, not really working well.
    enable_personal_messaging: false
    # The crew manager tab in the user frontend.
    enable_crew_manager: true

    # The role that will be applied.
    crew_manager_role: 'Crew Manager'
    
    # What is considered overlap? Only booked jobs if you ask me.
    job_overlap_booked_only: true

    # Job overlaps. A few options for it.
    job_overlap_same_day: false

    # Any job with less than these hours is considered an overlap
    # Any job within less than these hours is considered an overlap
    # Set 0 if pure overlap (Default)
    # job_overlap_hours: 4
    job_overlap_hours: 11

    bisonlab_reports:
        report_classes:
            - App\Lib\Reports\Reports
            # - CustomBundle\Lib\Reports\Reports
        # For generated reports, usuaslly uuseful to be able to grab from the
        # web.
        default_filestore: '%kernel.project_dir%/public/reports'

    crewcall.system_roles:
            ROLE_USER:
                label: 'Crewmember'
                description: 'User able to log into and use this application as crew member'
            ROLE_ADMIN:
                label: 'Admin'
                description: 'Admin User'
            ROLE_PERSON:
                label: 'Other'
                description: 'Person with other roles, like contact for an organization. Not able to log in.'

    # Stuff you can define in .env.local, if you want to.
    mailfrom: '%env(MAIL_FROM)%'
    mailname: '%env(MAIL_NAME)%'
